# Generated by Django 4.2.16 on 2024-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korean_app', '0003_quizlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizlog',
            old_name='question',
            new_name='sentence',
        ),
        migrations.AddField(
            model_name='quizlog',
            name='target_word',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
