# Generated by Django 4.2.16 on 2024-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korean_app', '0004_rename_question_quizlog_sentence_quizlog_target_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='nickname',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
